/**
 * Runtime-safe API route registry shared by servers and clients.
 * Request/response validation schemas live in the domain modules so browser
 * clients can consume routes without bundling server-side validators.
 */
const route = (method: string, path: string) => ({ method, path });
const path = <F extends (...parts: string[]) => string>(method: string, value: string, pathFor: F) => ({ method, path: value, pathFor });
const query = <F extends (...parts: any[]) => string>(method: string, value: string, pathFor: F) => ({ method, path: value, pathFor });
const segment = (value: string) => encodeURIComponent(value);

export const API_SPEC = {
  health: route("GET", "/health"), uploadedFile: path("GET", "/uploads/:name", (name: string) => `/uploads/${segment(name)}`),
  registerMember: route("POST", "/member/register"), loginMember: route("POST", "/member/login"), editMember: route("PATCH", "/member/edit"), addDeviceToken: route("POST", "/member/device-token"), removeDeviceToken: route("DELETE", "/member/device-token"), logoutMember: route("POST", "/member/logout"), refreshMember: query("GET", "/member/refresh", (token: string) => `/member/refresh?token=${segment(token)}`), memberInfo: route("GET", "/member/myInfo"), removeMember: route("DELETE", "/member/remove"),
  editProfile: path("PATCH", "/profile/:workspaceId", (workspaceId) => `/profile/${segment(workspaceId)}`), editStudentNumber: path("PATCH", "/profile/schidnum/:workspaceId", (workspaceId) => `/profile/schidnum/${segment(workspaceId)}`), myProfile: query("GET", "/profile/me", (workspaceId: string) => `/profile/me?workspaceId=${segment(workspaceId)}`), workspaceMember: query("GET", "/profile/others", (workspaceId: string, memberId: string) => `/profile/others?workspaceId=${segment(workspaceId)}&memberId=${segment(memberId)}`),
  createGroupRoom: route("POST", "/chat/group/create"), createPersonalRoom: route("POST", "/chat/personal/create"), groupRooms: path("GET", "/chat/group/search/:workspaceId", (id) => `/chat/group/search/${segment(id)}`), personalRooms: path("GET", "/chat/personal/search/:workspaceId", (id) => `/chat/personal/search/${segment(id)}`), searchGroupRooms: query("GET", "/chat/group/search", (workspaceId: string, word = "") => `/chat/group/search?workspace=${segment(workspaceId)}&word=${segment(word)}`), searchPersonalRooms: query("GET", "/chat/personal/search", (workspaceId: string, word = "") => `/chat/personal/search?workspace=${segment(workspaceId)}&word=${segment(word)}`), groupRoom: path("GET", "/chat/group/search/room/:roomId", (id) => `/chat/group/search/room/${segment(id)}`), personalRoom: path("GET", "/chat/personal/search/room/:roomId", (id) => `/chat/personal/search/room/${segment(id)}`), addGroupMembers: route("POST", "/chat/group/member/add"), removeGroupMembers: route("PATCH", "/chat/group/member/kick"), transferGroupAdmin: route("PATCH", "/chat/group/member/toss"), leaveGroupRoom: path("PATCH", "/chat/group/left/:roomId", (id) => `/chat/group/left/${segment(id)}`), messages: query("GET", "/message/search/:roomId", (id: string, timestamp?: string) => `/message/search/${segment(id)}${timestamp ? `?timestamp=${segment(timestamp)}` : ""}`), addMessageEmoji: route("PUT", "/message/emoji"), removeMessageEmoji: route("DELETE", "/message/emoji"), deleteMessage: route("DELETE", "/message/delete"),
  createNotification: route("POST", "/notification"), listNotifications: path("GET", "/notification/:workspaceId", (id) => `/notification/${segment(id)}`), updateNotification: route("PATCH", "/notification"), deleteNotification: path("DELETE", "/notification/:workspaceId/:id", (workspaceId, id) => `/notification/${segment(workspaceId)}/${segment(id)}`), toggleNotificationEmoji: route("PATCH", "/notification/emoji"),
  createTimetable: route("POST", "/timetable"), updateTimetable: route("PATCH", "/timetable"), deleteTimetable: path("DELETE", "/timetable/:id", (id) => `/timetable/${segment(id)}`), resetTimetable: query("POST", "/timetable/reset", (id: string) => `/timetable/reset?workspaceId=${segment(id)}`), dailyTimetable: query("GET", "/timetable/day", (id: string) => `/timetable/day?workspaceId=${segment(id)}`), weeklyTimetable: query("GET", "/timetable/weekend", (id: string) => `/timetable/weekend?workspaceId=${segment(id)}`), mealForDate: query("GET", "/meal", (id: string, date: string) => `/meal?workspaceId=${segment(id)}&date=${segment(date)}`), meals: query("GET", "/meal/all", (id: string, year?: number, month?: number) => `/meal/all?workspaceId=${segment(id)}${year !== undefined && month !== undefined ? `&year=${year}&month=${month}` : ""}`), resetMeals: path("POST", "/meal/reset/:workspaceId", (id) => `/meal/reset/${segment(id)}`), schedules: path("GET", "/schedule/:workspaceId", (id) => `/schedule/${segment(id)}`), monthSchedules: query("GET", "/schedule/month", (id: string, month: number) => `/schedule/month?workspaceId=${segment(id)}&month=${month}`),
  sendVerification: query("GET", "/email/send", (email: string) => `/email/send?email=${segment(email)}`), confirmVerification: route("POST", "/email/confirm"), authenticateOAuth: path("POST", "/oauth/:provider/authenticate", (provider) => `/oauth/${segment(provider)}/authenticate`), connectGoogle: route("POST", "/oauth/google/connect"), removeGoogleConnection: route("DELETE", "/oauth/google/remove"), googleConnection: route("GET", "/oauth/google/status"), askCatseugi: route("POST", "/ai"), uploadFile: path("POST", "/file/upload/:type", (type) => `/file/upload/${segment(type)}`),
  createTask: route("POST", "/task"), listTasks: path("GET", "/task/:workspaceId", (id) => `/task/${segment(id)}`), classroomTasks: route("GET", "/task/classroom"), createWorkspace: route("POST", "/workspace"), updateWorkspace: route("PATCH", "/workspace"), listWorkspaces: route("GET", "/workspace"), workspaceDetails: path("GET", "/workspace/:workspaceId", (id) => `/workspace/${segment(id)}`), deleteWorkspace: path("DELETE", "/workspace/:workspaceId", (id) => `/workspace/${segment(id)}`), joinWorkspace: route("POST", "/workspace/join"), workspaceMembers: query("GET", "/workspace/members", (id: string) => `/workspace/members?workspaceId=${segment(id)}`), workspaceMemberChart: query("GET", "/workspace/members/chart", (id: string) => `/workspace/members/chart?workspaceId=${segment(id)}`), workspaceNotificationPreference: path("GET", "/workspace/:workspaceId/notifications", (id) => `/workspace/${segment(id)}/notifications`), setWorkspaceNotificationPreference: path("PATCH", "/workspace/:workspaceId/notifications", (id) => `/workspace/${segment(id)}/notifications`), workspaceCode: path("GET", "/workspace/code/:workspaceId", (id) => `/workspace/code/${segment(id)}`), searchWorkspace: path("GET", "/workspace/search/:code", (code) => `/workspace/search/${segment(code)}`), approveWorkspaceMembers: route("PATCH", "/workspace/add"), rejectWorkspaceMembers: route("DELETE", "/workspace/cancel"), workspaceWaitlist: query("GET", "/workspace/wait-list", (id: string, role: string = "STUDENT") => `/workspace/wait-list?workspaceId=${segment(id)}&role=${segment(role)}`), updateWorkspaceMemberRole: route("PATCH", "/workspace/permission"), kickWorkspaceMembers: route("PATCH", "/workspace/kick"), myWaitingWorkspaces: route("GET", "/workspace/my/wait-list"),
} as const;
