import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, FlatList, Image, Linking, Platform, SafeAreaView, ScrollView, Share, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import * as SecureStore from "expo-secure-store";
import * as Notifications from "expo-notifications";
import * as DocumentPicker from "expo-document-picker";
import * as AppleAuthentication from "expo-apple-authentication";
import { GoogleSignin } from "@react-native-google-signin/google-signin";
import { type Member, type Role, type Room, type Workspace, type WorkspaceMemberChart } from "@seugi/contracts";
import { SeugiColor } from "@seugi/design-tokens";
import { Button, Card, WorkspaceRolePicker, type WorkspaceJoinRole } from "./src/components/ui";
import { GoogleAuthButton } from "./src/components/GoogleAuthButton";
import { AssignmentsScreen as Assignments } from "./src/screens/AssignmentsScreen";
import { CreateWorkspaceCard, PendingWorkspaceRequests, WorkspaceSetupScreen as WorkspaceSetup } from "./src/screens/WorkspaceSetupScreen";
import { NoticesScreen as Notices } from "./src/screens/NoticesScreen";
import { ChatScreen } from "./src/screens/ChatScreen";
import { ChatConversationScreen } from "./src/screens/ChatConversationScreen";
import { absoluteApiUrl } from "./src/utils/url";
import { GOOGLE_IOS_CLIENT_ID, GOOGLE_WEB_CLIENT_ID } from "./src/config";
import { Home, MealCalendar, TimetablePage } from "./src/screens/HomeScreen";
import { api } from "./src/services/api";
import { localDateKey } from "./src/utils/date";
import { refreshHomeWidgets } from "./src/widgets/refresh";

type Tab = "home" | "meals" | "timetable" | "tasks" | "chat" | "notice" | "profile";
const tabs: Array<[Tab, string]> = [["home", "홈"], ["meals", "급식"], ["timetable", "시간표"], ["tasks", "과제"], ["chat", "채팅"], ["notice", "공지"], ["profile", "프로필"]];
const accessTokenKey = "seugi.access-token";
const refreshTokenKey = "seugi.refresh-token";
const workspaceIdKey = "seugi.workspace-id";
if (GOOGLE_WEB_CLIENT_ID) GoogleSignin.configure({ webClientId: GOOGLE_WEB_CLIENT_ID, iosClientId: GOOGLE_IOS_CLIENT_ID || undefined, offlineAccess: true, forceCodeForRefreshToken: true, scopes: ["https://www.googleapis.com/auth/classroom.courses.readonly", "https://www.googleapis.com/auth/classroom.coursework.me.readonly", "https://www.googleapis.com/auth/classroom.coursework.students.readonly"] });
Notifications.setNotificationHandler({ handleNotification: async () => ({ shouldShowAlert: true, shouldShowBanner: true, shouldShowList: true, shouldPlaySound: true, shouldSetBadge: false }) });

export default function App() {
  const [tab, setTab] = useState<Tab>("home");
  const [authenticated, setAuthenticated] = useState(false);
  const [workspace, setWorkspace] = useState<Workspace>();
  const [workspaces, setWorkspaces] = useState<Workspace[]>([]);
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [name, setName] = useState(""); const [code, setCode] = useState("");
  const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [hydrated, setHydrated] = useState(false); const [deviceToken, setDeviceToken] = useState<string>();
  const [appleAvailable, setAppleAvailable] = useState(false);
  const signedIn = authenticated && !!workspace;
  const load = useCallback(async () => { const list = (await api.workspaces()).data ?? []; setWorkspaces(list); const storedId = await SecureStore.getItemAsync(workspaceIdKey); const selected = list.find((item) => item.id === storedId) ?? list[0]; setWorkspace((current) => current && list.find((item) => item.id === current.id) || selected); if (selected) await SecureStore.setItemAsync(workspaceIdKey, selected.id); }, []);
  const selectWorkspace = useCallback((selected: Workspace) => { setWorkspace(selected); void SecureStore.setItemAsync(workspaceIdKey, selected.id).then(() => refreshHomeWidgets()).catch(() => undefined); }, []);
  useEffect(() => { let active = true; (async () => { let token = await SecureStore.getItemAsync(accessTokenKey); const refreshToken = await SecureStore.getItemAsync(refreshTokenKey); api.setRefreshToken(refreshToken ?? undefined); if (token) { api.setToken(token); try { await load(); } catch { if (!refreshToken) throw new Error("세션이 만료되었습니다"); const refreshed = await api.refreshAccessToken(refreshToken); if (!refreshed.data) throw new Error("세션을 갱신하지 못했습니다"); token = refreshed.data; api.setToken(token); await SecureStore.setItemAsync(accessTokenKey, token); await load(); } if (active) setAuthenticated(true); } if (active) setHydrated(true); })().catch(async () => { api.setToken(); api.setRefreshToken(); await SecureStore.deleteItemAsync(accessTokenKey); await SecureStore.deleteItemAsync(refreshTokenKey); if (active) setHydrated(true); }); return () => { active = false; }; }, [load]);
  useEffect(() => { if (!signedIn) return; let active = true; void refreshHomeWidgets().catch(() => undefined); (async () => { if (Platform.OS === "android") await Notifications.setNotificationChannelAsync("default", { name: "기본", importance: Notifications.AndroidImportance.DEFAULT }); const current = await Notifications.getPermissionsAsync(); const permission = current.status === "granted" ? current : await Notifications.requestPermissionsAsync(); if (permission.status !== "granted") return; const token = (await Notifications.getExpoPushTokenAsync()).data; await api.registerDeviceToken(token); if (active) setDeviceToken(token); })().catch(() => undefined); return () => { active = false; }; }, [signedIn]);
  const persistSession = useCallback(async (token?: string, refreshToken?: string) => { if (!token) throw new Error("액세스 토큰을 받지 못했습니다"); api.setToken(token); api.setRefreshToken(refreshToken); await SecureStore.setItemAsync(accessTokenKey, token); if (refreshToken) await SecureStore.setItemAsync(refreshTokenKey, refreshToken); await load(); setAuthenticated(true); }, [load]);
  const authenticate = useCallback(async (register = false) => { setLoading(true); setError(""); try { const response = register ? await api.register({ email, password, name, code }) : await api.login({ email, password }); await persistSession(response.data?.accessToken, response.data?.refreshToken); } catch (reason) { setError(reason instanceof Error ? reason.message : "로그인에 실패했습니다"); } finally { setLoading(false); } }, [email, password, name, code, persistSession]);
  const authenticateGoogle = useCallback(async (code: string) => { setLoading(true); setError(""); try { const response = await api.authenticateGoogle({ code, platform: Platform.OS === "ios" ? "IOS" : "ANDROID", name: name || undefined }); await persistSession(response.data?.accessToken, response.data?.refreshToken); } catch (reason) { setError(reason instanceof Error ? reason.message : "Google 로그인에 실패했습니다"); } finally { setLoading(false); } }, [name, persistSession]);
  useEffect(() => { if (Platform.OS === "ios") AppleAuthentication.isAvailableAsync().then(setAppleAvailable).catch(() => setAppleAvailable(false)); }, []);
  const authenticateApple = useCallback(async () => {
    if (loading) return;
    setLoading(true); setError("");
    try {
      const credential = await AppleAuthentication.signInAsync({ requestedScopes: [AppleAuthentication.AppleAuthenticationScope.FULL_NAME, AppleAuthentication.AppleAuthenticationScope.EMAIL] });
      if (!credential.authorizationCode) throw new Error("Apple 인증 코드를 받지 못했습니다");
      const fullName = credential.fullName;
      const appleName = fullName ? [fullName.familyName, fullName.givenName].filter(Boolean).join("") : "";
      const response = await api.authenticateApple({ code: credential.authorizationCode, platform: "IOS", name: appleName || name || undefined });
      await persistSession(response.data?.accessToken, response.data?.refreshToken);
    } catch (reason) {
      if (!(reason instanceof Error) || !("code" in reason) || reason.code !== "ERR_REQUEST_CANCELED") setError(reason instanceof Error ? reason.message : "Apple 로그인에 실패했습니다");
    } finally { setLoading(false); }
  }, [loading, name, persistSession]);
  if (!hydrated) return <SafeAreaView style={styles.auth}><ActivityIndicator size="large" color={SeugiColor.Primary500} /><Text style={styles.subtitle}>로그인 정보를 확인하는 중…</Text></SafeAreaView>;
  if (!authenticated) return <SafeAreaView style={styles.auth}>
    <Text style={styles.logo}>스기</Text><Text style={styles.subtitle}>학교의 모든 소통을 한 곳에서</Text>
    {appleAvailable ? <AppleAuthentication.AppleAuthenticationButton buttonType={AppleAuthentication.AppleAuthenticationButtonType.SIGN_IN} buttonStyle={AppleAuthentication.AppleAuthenticationButtonStyle.BLACK} cornerRadius={10} style={{ width: "100%", height: 48, marginBottom: 10 }} onPress={authenticateApple} /> : null}
    {Platform.OS !== "web" && GOOGLE_WEB_CLIENT_ID ? <GoogleAuthButton label="Google로 로그인" onCode={authenticateGoogle} onError={setError} disabled={loading} /> : null}
    <TextInput placeholder="이메일" autoCapitalize="none" style={styles.input} value={email} onChangeText={setEmail} /><TextInput placeholder="비밀번호 (8자 이상)" secureTextEntry style={styles.input} value={password} onChangeText={setPassword} /><TextInput placeholder="이름 (회원가입 시)" style={styles.input} value={name} onChangeText={setName} /><TextInput placeholder="이메일 인증 코드 (회원가입 시)" keyboardType="number-pad" style={styles.input} value={code} onChangeText={setCode} />
    {error ? <Text style={styles.error}>{error}</Text> : null}<Button label="인증 코드 보내기" kind="secondary" onPress={() => api.sendVerification(email).then(() => setError("인증 코드를 발송했습니다.")).catch((e) => setError(e.message))} disabled={!email || loading} /><Button label={loading ? "처리 중…" : "로그인"} onPress={() => authenticate(false)} disabled={loading} /><Button label="이메일로 회원가입" kind="secondary" onPress={() => authenticate(true)} disabled={loading} />
  </SafeAreaView>;
  if (!workspace) return <WorkspaceSetup onCreated={load} onLogout={async () => { api.setToken(); api.setRefreshToken(); await SecureStore.deleteItemAsync(accessTokenKey); await SecureStore.deleteItemAsync(refreshTokenKey); setAuthenticated(false); }} />;
  return <SafeAreaView style={styles.page}><View style={styles.header}><Text style={styles.title}>{workspace?.name ?? "스기"}</Text><TouchableOpacity onPress={() => load().catch((reason) => setError(String(reason)))}><Text style={styles.link}>새로고침</Text></TouchableOpacity></View>{error ? <Text style={styles.error}>{error}</Text> : null}{tab === "home" && <Home workspace={workspace!} />}{tab === "meals" && <MealCalendar workspace={workspace!} />}{tab === "timetable" && <TimetablePage workspace={workspace!} />}{tab === "tasks" && <Assignments workspace={workspace!} />}{tab === "chat" && <Chat workspace={workspace!} />}{tab === "notice" && <Notices workspace={workspace!} />}{tab === "profile" && <Profile workspaces={workspaces} workspace={workspace!} onSelect={selectWorkspace} onReload={load} onLogout={async () => { if (deviceToken) await api.removeDeviceToken(deviceToken).catch(() => undefined); api.setToken(); api.setRefreshToken(); await SecureStore.deleteItemAsync(accessTokenKey); await SecureStore.deleteItemAsync(refreshTokenKey); await SecureStore.deleteItemAsync(workspaceIdKey); setDeviceToken(undefined); setWorkspace(undefined); setAuthenticated(false); void refreshHomeWidgets().catch(() => undefined); }} />}<View style={styles.tabbar}>{tabs.map(([key, label]) => <TouchableOpacity key={key} onPress={() => setTab(key)} style={styles.tab}><Text style={tab === key ? styles.activeTab : styles.inactiveTab}>{label}</Text></TouchableOpacity>)}</View></SafeAreaView>;
}


function Chat({ workspace }: { workspace: Workspace }) {
  return <ChatScreen workspace={workspace} RoomMessagesComponent={RoomMessages} />;
}
function RoomMessages({ room, onBack }: { room: Room; onBack: () => void }) {
  return <ChatConversationScreen room={room} onBack={onBack} />;
}
function Profile({ workspaces, workspace, onSelect, onReload, onLogout }: { workspaces: Workspace[]; workspace: Workspace; onSelect: (value: Workspace) => void; onReload: () => Promise<void>; onLogout: () => void | Promise<void> }) {
  const [inviteCode, setInviteCode] = useState("");
  const [joinRole, setJoinRole] = useState<WorkspaceJoinRole>("STUDENT");
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const join = async () => {
    if (!inviteCode.trim() || busy) return;
    setBusy(true); setMessage("");
    try { await api.joinWorkspace({ code: inviteCode.trim().toUpperCase(), role: joinRole }); setInviteCode(""); setMessage("가입 신청을 보냈습니다. 관리자 승인 후 목록에서 선택할 수 있습니다."); }
    catch (e) { setMessage(e instanceof Error ? e.message : "가입 신청에 실패했습니다"); }
    finally { setBusy(false); }
  };
  const signOut = async () => { await api.logout().catch(() => undefined); await onLogout(); };
  const openPolicy = (url: string) => { void Linking.openURL(url).catch(() => setMessage("정책 페이지를 열지 못했습니다. 잠시 후 다시 시도해 주세요.")); };
  const withdraw = () => Alert.alert("회원 탈퇴", "계정과 연결된 데이터에 접근할 수 없게 됩니다. 탈퇴를 진행할까요?", [
    { text: "취소", style: "cancel" },
    { text: "탈퇴", style: "destructive", onPress: () => { void (async () => { setBusy(true); setMessage(""); try { await api.removeMember(); await onLogout(); } catch (e) { setMessage(e instanceof Error ? e.message : "회원 탈퇴에 실패했습니다"); } finally { setBusy(false); } })(); } },
  ]);
  return <ScrollView style={styles.content}><ProfileEditor workspace={workspace} />
    <Card title="워크스페이스">{workspaces.map((item) => <TouchableOpacity key={item.id} onPress={() => onSelect(item)}><Text style={item.id === workspace.id ? styles.activeTab : styles.rowTitle}>{item.name}</Text></TouchableOpacity>)}</Card>
    <WorkspaceEditor workspace={workspace} onSaved={onReload} />
    <PendingWorkspaceRequests onChanged={onReload} />
    <WorkspaceInviteCode workspace={workspace} />
    <JoinRequests workspace={workspace} /><WorkspaceMembers workspace={workspace} /><WorkspaceOrganizationChart workspace={workspace} /><WorkspaceNotificationSettings workspace={workspace} />
    <CreateWorkspaceCard onCreated={onReload} />
    <Card title="초대 코드로 가입"><TextInput value={inviteCode} onChangeText={setInviteCode} autoCapitalize="characters" style={styles.input} placeholder="초대 코드" /><WorkspaceRolePicker value={joinRole} onChange={setJoinRole} /><Button label={busy ? "처리 중…" : "가입 신청"} onPress={join} disabled={busy || !inviteCode.trim()} /></Card>
    {message ? <Text style={styles.answer}>{message}</Text> : null}
    <Card title="안내"><Button label="개인정보 처리 방침" kind="secondary" onPress={() => openPolicy("https://byungjjun.notion.site/58f95c1209fb48b4b74434701290f838")} /><Button label="서비스 운영 정책" kind="secondary" onPress={() => openPolicy("https://byungjjun.notion.site/5ba79e224f53439bbfa3607e581fe6bf")} /></Card>
    <Button label="로그아웃" kind="secondary" onPress={signOut} disabled={busy} />
    <Button label="회원 탈퇴" kind="secondary" onPress={withdraw} disabled={busy} />
  </ScrollView>;
}
function WorkspaceEditor({ workspace, onSaved }: { workspace: Workspace; onSaved: () => Promise<void> }) {
  const [name, setName] = useState(workspace.name); const [image, setImage] = useState<{ uri: string; name: string; mimeType?: string }>(); const [canEdit, setCanEdit] = useState(false); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  useEffect(() => { let active = true; Promise.all([api.memberInfo(), api.myProfile(workspace.id)]).then(([member, profile]) => active && setCanEdit(member.data?.id === workspace.ownerId || profile.data?.role === "MIDDLE_ADMIN")).catch(() => undefined); return () => { active = false; }; }, [workspace.id, workspace.ownerId]);
  useEffect(() => { setName(workspace.name); setImage(undefined); }, [workspace.id, workspace.name]);
  const pickImage = async () => { try { const result = await DocumentPicker.getDocumentAsync({ type: "image/*", copyToCacheDirectory: true, multiple: false }); if (!result.canceled && result.assets[0]) { const asset = result.assets[0]; setImage({ uri: asset.uri, name: asset.name, mimeType: asset.mimeType ?? undefined }); } } catch (error) { setNotice(error instanceof Error ? error.message : "학교 이미지를 선택하지 못했습니다"); } };
  const save = async () => { if (busy || !name.trim()) return; setBusy(true); setNotice(""); try { let imageUrl: string | undefined; if (image) { const form = new FormData(); form.append("file", { uri: image.uri, name: image.name, type: image.mimeType ?? "image/jpeg" } as unknown as Blob); const uploaded = await api.uploadFile("IMAGE", form); imageUrl = uploaded.data?.url; if (!imageUrl) throw new Error("이미지 업로드 응답이 올바르지 않습니다"); } await api.updateWorkspace({ workspaceId: workspace.id, name: name.trim(), image: imageUrl }); await onSaved(); setImage(undefined); setNotice("워크스페이스 정보를 저장했습니다."); } catch (error) { setNotice(error instanceof Error ? error.message : "워크스페이스 정보를 저장하지 못했습니다"); } finally { setBusy(false); } };
  if (!canEdit) return null;
  return <Card title="워크스페이스 정보 수정"><TextInput value={name} onChangeText={setName} style={styles.input} placeholder="워크스페이스 이름" maxLength={80} /><TouchableOpacity onPress={() => void pickImage()} disabled={busy} style={{ alignItems: "center", paddingVertical: 8 }}>{image ? <Image source={{ uri: image.uri }} style={{ width: 72, height: 72, borderRadius: 36 }} /> : workspace.image ? <Image source={{ uri: absoluteApiUrl(workspace.image) }} style={{ width: 72, height: 72, borderRadius: 36 }} /> : <Text style={styles.link}>학교 이미지 추가</Text>}<Text style={styles.link}>{image || workspace.image ? "이미지 변경" : "학교 이미지 추가 (선택)"}</Text></TouchableOpacity><Button label={busy ? "저장 중…" : "워크스페이스 저장"} onPress={() => void save()} disabled={busy || !name.trim()} />{notice ? <Text style={notice.includes("저장했습니다") ? styles.answer : styles.error}>{notice}</Text> : null}</Card>;
}
function WorkspaceOrganizationChart({ workspace }: { workspace: Workspace }) {
  const [chart, setChart] = useState<WorkspaceMemberChart>(); const [error, setError] = useState("");
  useEffect(() => { let active = true; api.workspaceMemberChart(workspace.id).then((result) => active && setChart(result.data)).catch((reason) => active && setError(reason instanceof Error ? reason.message : "조직도를 불러오지 못했습니다")); return () => { active = false; }; }, [workspace.id]);
  const sections: Array<[keyof WorkspaceMemberChart, string]> = [["admin", "관리자"], ["middleAdmin", "중간관리자"], ["teachers", "교사"], ["students", "학생"]];
  return <Card title="워크스페이스 조직도">{error ? <Text style={styles.error}>{error}</Text> : !chart ? <Text style={styles.muted}>불러오는 중…</Text> : sections.map(([key, title]) => { const groups = chart[key]; return <View key={key}><Text style={styles.rowTitle}>{title}</Text>{Object.entries(groups).length ? Object.entries(groups).map(([belong, people]) => <View key={`${key}-${belong}`} style={{ paddingLeft: 12 }}><Text style={styles.muted}>{belong}</Text>{people.map((person) => <Text key={person.member.id}>{person.member.name}{person.spot ? ` · ${person.spot}` : ""}{person.status ? ` — ${person.status}` : ""}</Text>)}</View>) : <Text style={styles.muted}>등록된 구성원이 없습니다.</Text>}</View>; })}</Card>;
}
function WorkspaceNotificationSettings({ workspace }: { workspace: Workspace }) { const [enabled, setEnabled] = useState(true); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); useEffect(() => { let active = true; api.workspaceNotificationPreference(workspace.id).then((result) => { if (active) setEnabled(result.data ?? true); }).catch((error) => active && setNotice(error instanceof Error ? error.message : "알림 설정을 불러오지 못했습니다")); return () => { active = false; }; }, [workspace.id]); const toggle = async () => { if (busy) return; setBusy(true); setNotice(""); try { const result = await api.setWorkspaceNotificationPreference(workspace.id, !enabled); setEnabled(result.data ?? !enabled); } catch (error) { setNotice(error instanceof Error ? error.message : "알림 설정을 저장하지 못했습니다"); } finally { setBusy(false); } }; return <Card title="워크스페이스 알림"><Text style={styles.muted}>이 워크스페이스의 공지와 채팅 푸시 알림</Text><Button label={busy ? "저장 중…" : enabled ? "알림 켜짐 · 끄기" : "알림 꺼짐 · 켜기"} kind={enabled ? "primary" : "secondary"} onPress={toggle} disabled={busy} />{notice ? <Text style={styles.error}>{notice}</Text> : null}</Card>; }
function WorkspaceInviteCode({ workspace }: { workspace: Workspace }) { const [code, setCode] = useState(""); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const load = useCallback(async () => { setBusy(true); setNotice(""); try { const result = await api.workspaceCode(workspace.id); setCode(result.data ?? ""); } catch (error) { setNotice(error instanceof Error ? error.message : "초대 코드를 불러오지 못했습니다"); } finally { setBusy(false); } }, [workspace.id]); useEffect(() => { setCode(""); void load(); }, [load]); const share = async () => { if (!code) return; try { await Share.share({ message: `스기 ${workspace.name} 워크스페이스 초대 코드: ${code}` }); } catch (error) { setNotice(error instanceof Error ? error.message : "초대 코드를 공유하지 못했습니다"); } }; return <Card title="구성원 초대"><Text style={styles.muted}>초대 코드를 공유하면 다른 구성원이 가입을 신청할 수 있습니다.</Text>{code ? <><Text selectable style={styles.rowTitle}>{code}</Text><Button label="초대 코드 공유" kind="secondary" onPress={share} /></> : <Button label={busy ? "불러오는 중…" : "초대 코드 보기"} kind="secondary" onPress={() => void load()} disabled={busy} />}{notice ? <Text style={styles.error}>{notice}</Text> : null}</Card>; }
function WorkspaceMembers({ workspace }: { workspace: Workspace }) { const [members, setMembers] = useState<Member[]>([]); const [isOwner, setIsOwner] = useState(false); const [busyId, setBusyId] = useState(""); const [notice, setNotice] = useState(""); const refresh = useCallback(async () => { const [info, result] = await Promise.all([api.memberInfo(), api.workspaceMembers(workspace.id)]); setIsOwner(info.data?.id === workspace.ownerId); setMembers((result.data ?? []).map((member) => ({ ...member, role: member.id === workspace.ownerId ? "ADMIN" : member.role ?? "STUDENT" }))); }, [workspace.id, workspace.ownerId]); useEffect(() => { refresh().catch((error) => setNotice(error instanceof Error ? error.message : "구성원 목록을 불러오지 못했습니다")); }, [refresh]); const roleName = (role?: Role) => role === "ADMIN" ? "관리자" : role === "MIDDLE_ADMIN" ? "중간관리자" : role === "TEACHER" ? "교사" : "학생"; const setRole = async (member: Member, role: Role) => { if (busyId) return; setBusyId(member.id); setNotice(""); try { await api.setWorkspaceMemberRole(workspace.id, member.id, role); await refresh(); } catch (error) { setNotice(error instanceof Error ? error.message : "권한을 변경하지 못했습니다"); } finally { setBusyId(""); } }; const remove = (member: Member) => Alert.alert("구성원 내보내기", `${member.name}님을 워크스페이스에서 내보낼까요?`, [{ text: "취소", style: "cancel" }, { text: "내보내기", style: "destructive", onPress: () => { void (async () => { setBusyId(member.id); setNotice(""); try { await api.removeWorkspaceMember(workspace.id, member.id); await refresh(); } catch (error) { setNotice(error instanceof Error ? error.message : "구성원을 내보내지 못했습니다"); } finally { setBusyId(""); } })(); } }]); return <Card title="워크스페이스 구성원">{members.map((member) => <View key={member.id} style={styles.memberRow}><Text style={styles.rowTitle}>{member.name} · {roleName(member.role)}</Text>{isOwner && member.id !== workspace.ownerId ? <><View style={styles.memberActions}>{(["STUDENT", "TEACHER", "MIDDLE_ADMIN"] as const).map((role) => <TouchableOpacity key={role} disabled={!!busyId} onPress={() => setRole(member, role)}><Text style={member.role === role ? styles.activeTab : styles.link}>{role === "STUDENT" ? "학생" : role === "TEACHER" ? "교사" : "관리자"}</Text></TouchableOpacity>)}</View><TouchableOpacity disabled={!!busyId} onPress={() => remove(member)}><Text style={styles.error}>내보내기</Text></TouchableOpacity></> : null}</View>)}{notice ? <Text style={styles.error}>{notice}</Text> : null}</Card>; }
function ProfileEditor({ workspace }: { workspace: Workspace }) {
  const [name, setName] = useState(""); const [grade, setGrade] = useState(""); const [classNumber, setClassNumber] = useState(""); const [number, setNumber] = useState("");
  const [picture, setPicture] = useState(""); const [photoBusy, setPhotoBusy] = useState(false);
  const [status, setStatus] = useState(""); const [nick, setNick] = useState(""); const [spot, setSpot] = useState(""); const [belong, setBelong] = useState(""); const [phone, setPhone] = useState(""); const [wire, setWire] = useState(""); const [location, setLocation] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; Promise.all([api.memberInfo(), api.myProfile(workspace.id)]).then(([member, profile]) => { if (!active) return; setName(member.data?.name ?? ""); setPicture(member.data?.picture ?? ""); setGrade(profile.data?.grade ? String(profile.data.grade) : ""); setClassNumber(profile.data?.class ? String(profile.data.class) : ""); setNumber(profile.data?.number ? String(profile.data.number) : ""); setStatus(profile.data?.status ?? ""); setNick(profile.data?.nick ?? ""); setSpot(profile.data?.spot ?? ""); setBelong(profile.data?.belong ?? ""); setPhone(profile.data?.phone ?? ""); setWire(profile.data?.wire ?? ""); setLocation(profile.data?.location ?? ""); }).catch(() => undefined); return () => { active = false; }; }, [workspace.id]);
  const pickPhoto = async () => {
    if (photoBusy) return;
    setPhotoBusy(true); setNotice("");
    try {
      const result = await DocumentPicker.getDocumentAsync({ type: "image/*", copyToCacheDirectory: true, multiple: false });
      if (result.canceled || !result.assets[0]) return;
      const asset = result.assets[0]; const form = new FormData();
      form.append("file", { uri: asset.uri, name: asset.name, type: asset.mimeType ?? "image/jpeg" } as unknown as Blob);
      const uploaded = await api.uploadFile("PROFILE", form);
      if (!uploaded.data?.url) throw new Error("이미지 업로드 응답이 올바르지 않습니다");
      await api.editMember({ picture: uploaded.data.url }); setPicture(uploaded.data.url); setNotice("프로필 사진을 변경했습니다.");
    } catch (e) { setNotice(e instanceof Error ? e.message : "프로필 사진을 변경하지 못했습니다"); }
    finally { setPhotoBusy(false); }
  };
  const save = async () => { if (busy) return; setBusy(true); setNotice(""); try { if (!name.trim()) throw new Error("이름을 입력해 주세요"); const hasStudentNumber = !!(grade || classNumber || number); if (hasStudentNumber && [grade, classNumber, number].some((value) => !/^\d+$/.test(value) || Number(value) < 1)) throw new Error("학년·반·번호를 모두 올바르게 입력해 주세요"); await api.editMember({ name: name.trim() }); await api.editProfile(workspace.id, { status, nick, spot, belong, phone, wire, location, ...(hasStudentNumber ? { grade: Number(grade), class: Number(classNumber), number: Number(number) } : {}) }); setNotice("프로필을 저장했습니다."); } catch (e) { setNotice(e instanceof Error ? e.message : "프로필 저장에 실패했습니다"); } finally { setBusy(false); } };
  return <Card title="내 프로필"><View style={{ alignItems: "center", gap: 8 }}><TouchableOpacity onPress={pickPhoto} disabled={photoBusy}>{picture ? <Image source={{ uri: absoluteApiUrl(picture) }} style={{ width: 88, height: 88, borderRadius: 44, backgroundColor: SeugiColor.Gray300 }} /> : <View style={{ width: 88, height: 88, borderRadius: 44, backgroundColor: SeugiColor.Primary100, alignItems: "center", justifyContent: "center" }}><Text style={styles.link}>사진 추가</Text></View>}</TouchableOpacity><Text style={styles.muted}>{photoBusy ? "사진 업로드 중…" : "프로필 사진 변경"}</Text></View><TextInput value={name} onChangeText={setName} style={styles.input} placeholder="이름" /><TextInput value={nick} onChangeText={setNick} style={styles.input} placeholder="닉네임" /><TextInput value={status} onChangeText={setStatus} style={styles.input} placeholder="상태 메시지" /><View style={styles.row}><TextInput value={grade} onChangeText={setGrade} keyboardType="number-pad" style={[styles.input, styles.numberInput]} placeholder="학년" /><TextInput value={classNumber} onChangeText={setClassNumber} keyboardType="number-pad" style={[styles.input, styles.numberInput]} placeholder="반" /><TextInput value={number} onChangeText={setNumber} keyboardType="number-pad" style={[styles.input, styles.numberInput]} placeholder="번호" /></View><TextInput value={spot} onChangeText={setSpot} style={styles.input} placeholder="직위" /><TextInput value={belong} onChangeText={setBelong} style={styles.input} placeholder="소속" /><TextInput value={phone} onChangeText={setPhone} keyboardType="phone-pad" style={styles.input} placeholder="휴대전화번호" /><TextInput value={wire} onChangeText={setWire} keyboardType="phone-pad" style={styles.input} placeholder="유선전화번호" /><TextInput value={location} onChangeText={setLocation} style={styles.input} placeholder="근무 위치" /><Button label={busy ? "저장 중…" : "프로필 저장"} onPress={save} disabled={busy} />{notice ? <Text style={styles.answer}>{notice}</Text> : null}</Card>;
}
function JoinRequests({ workspace }: { workspace: Workspace }) { type RequestRole = "STUDENT" | "TEACHER" | "MIDDLE_ADMIN"; const [role, setRole] = useState<Role>(); const [requestRole, setRequestRole] = useState<RequestRole>("STUDENT"); const [members, setMembers] = useState<Member[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); useEffect(() => { let active = true; Promise.all([api.memberInfo(), api.myProfile(workspace.id)]).then(([member, profile]) => { if (active) setRole(workspace.ownerId === member.data?.id ? "ADMIN" : profile.data?.role ?? "STUDENT"); }).catch(() => active && setRole("STUDENT")); return () => { active = false; }; }, [workspace.id, workspace.ownerId]); const options: RequestRole[] = role === "ADMIN" ? ["STUDENT", "TEACHER", "MIDDLE_ADMIN"] : role === "MIDDLE_ADMIN" ? ["STUDENT", "TEACHER"] : role === "TEACHER" ? ["STUDENT"] : []; useEffect(() => { if (!options.includes(requestRole)) { setRequestRole("STUDENT"); setMembers([]); return; } let active = true; api.waitlist(workspace.id, requestRole).then((result) => active && setMembers(result.data ?? [])).catch(() => active && setMembers([])); return () => { active = false; }; }, [workspace.id, requestRole, role]); const update = async (memberId: string, approve: boolean) => { setBusy(true); setMessage(""); try { if (approve) await api.approveWorkspaceMember(workspace.id, memberId, requestRole); else await api.rejectWorkspaceMember(workspace.id, memberId, requestRole); setMembers((current) => current.filter((member) => member.id !== memberId)); } catch (e) { setMessage(e instanceof Error ? e.message : "요청 처리에 실패했습니다"); } finally { setBusy(false); } }; if (!role || options.length === 0) return null; return <Card title="가입 신청 관리"><View style={styles.row}>{options.map((option) => <TouchableOpacity key={option} onPress={() => setRequestRole(option)}><Text style={requestRole === option ? styles.activeTab : styles.inactiveTab}>{option === "STUDENT" ? "학생" : option === "TEACHER" ? "교사" : "관리자"}</Text></TouchableOpacity>)}</View>{members.length ? members.map((member) => <View key={member.id} style={styles.row}><Text style={styles.rowTitle}>{member.name} · {member.email}</Text><View><Button label="승인" onPress={() => update(member.id, true)} disabled={busy} /><Button label="거절" kind="secondary" onPress={() => update(member.id, false)} disabled={busy} /></View></View>) : <Text style={styles.muted}>대기 중인 가입 신청이 없습니다.</Text>}{message ? <Text style={styles.error}>{message}</Text> : null}</Card>; }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: SeugiColor.Primary050 }, auth: { flex: 1, justifyContent: "center", padding: 24, backgroundColor: SeugiColor.Primary050 }, logo: { color: SeugiColor.Primary500, fontWeight: "800", fontSize: 36, textAlign: "center" }, subtitle: { textAlign: "center", color: SeugiColor.Gray600, marginVertical: 24 }, header: { height: 58, backgroundColor: SeugiColor.White, paddingHorizontal: 20, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, title: { fontSize: 20, fontWeight: "700" }, link: { color: SeugiColor.Primary500 }, content: { flex: 1, padding: 16 }, input: { backgroundColor: SeugiColor.White, borderWidth: 1, borderColor: SeugiColor.Gray300, borderRadius: 10, padding: 13, marginBottom: 10 }, numberInput: { flex: 1, minWidth: 0 }, button: { backgroundColor: SeugiColor.Primary500, padding: 14, borderRadius: 10, alignItems: "center", marginBottom: 10 }, secondary: { backgroundColor: SeugiColor.Primary100 }, buttonText: { color: SeugiColor.White, fontWeight: "700" }, secondaryText: { color: SeugiColor.Primary500, fontWeight: "700" }, disabled: { opacity: 0.5 }, card: { backgroundColor: SeugiColor.White, borderRadius: 14, padding: 16, marginBottom: 12, gap: 8 }, cardTitle: { fontSize: 17, fontWeight: "700" }, tabbar: { height: 64, flexDirection: "row", backgroundColor: SeugiColor.White, borderTopWidth: 1, borderColor: SeugiColor.Gray300 }, tab: { flex: 1, justifyContent: "center", alignItems: "center" }, activeTab: { color: SeugiColor.Primary500, fontWeight: "700" }, inactiveTab: { color: SeugiColor.Gray500 }, row: { backgroundColor: SeugiColor.White, padding: 16, marginBottom: 8, borderRadius: 12, flexDirection: "row", justifyContent: "space-between" }, memberRow: { borderBottomWidth: 1, borderColor: SeugiColor.Gray100, paddingVertical: 12, gap: 8 }, memberActions: { flexDirection: "row", gap: 14 }, rowTitle: { fontWeight: "600" }, muted: { color: SeugiColor.Gray500, fontSize: 12 }, error: { color: SeugiColor.Red500, marginVertical: 8, textAlign: "center" }, empty: { color: SeugiColor.Gray600, textAlign: "center", padding: 30 }, answer: { backgroundColor: SeugiColor.Primary100, padding: 10, borderRadius: 8 }, reactions: { flexDirection: "row", flexWrap: "wrap", gap: 12, paddingTop: 6 }, chatPage: { flex: 1 }, chatHeader: { backgroundColor: SeugiColor.White, padding: 16, flexDirection: "row", gap: 16, alignItems: "center" }, message: { backgroundColor: SeugiColor.White, borderRadius: 12, padding: 12, marginBottom: 8, alignSelf: "flex-start", maxWidth: "85%" }, composer: { flexDirection: "row", padding: 10, gap: 8, backgroundColor: SeugiColor.White, alignItems: "center" }, composerInput: { flex: 1, marginBottom: 0 } });
