import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, FlatList, SafeAreaView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { SeugiApi } from "@seugi/api-client";
import type { Notification, Room, Task, Timetable, Workspace } from "@seugi/contracts";
import { API_URL } from "./src/config";

type Tab = "home" | "chat" | "notice" | "profile";
const tabs: Array<[Tab, string]> = [["home", "홈"], ["chat", "채팅"], ["notice", "공지"], ["profile", "프로필"]];
const api = new SeugiApi(API_URL);

export default function App() {
  const [tab, setTab] = useState<Tab>("home");
  const [workspace, setWorkspace] = useState<Workspace>();
  const [workspaces, setWorkspaces] = useState<Workspace[]>([]);
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [name, setName] = useState("");
  const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const signedIn = !!workspace;
  const load = useCallback(async () => { const list = (await api.workspaces()).data ?? []; setWorkspaces(list); setWorkspace((current) => current && list.find((item) => item.id === current.id) || list[0]); }, []);
  const authenticate = useCallback(async (register = false) => { setLoading(true); setError(""); try { const response = register ? await api.register({ email, password, name }) : await api.login({ email, password }); api.setToken(response.data?.accessToken); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "로그인에 실패했습니다"); } finally { setLoading(false); } }, [email, password, name, load]);
  if (!signedIn) return <SafeAreaView style={styles.auth}><Text style={styles.logo}>스기</Text><Text style={styles.subtitle}>학교의 모든 소통을 한 곳에서</Text><TextInput placeholder="이메일" autoCapitalize="none" style={styles.input} value={email} onChangeText={setEmail} /><TextInput placeholder="비밀번호 (8자 이상)" secureTextEntry style={styles.input} value={password} onChangeText={setPassword} /><TextInput placeholder="이름 (회원가입 시)" style={styles.input} value={name} onChangeText={setName} />{error ? <Text style={styles.error}>{error}</Text> : null}<Button label={loading ? "처리 중…" : "로그인"} onPress={() => authenticate(false)} disabled={loading} /><Button label="이메일로 회원가입" kind="secondary" onPress={() => authenticate(true)} disabled={loading} /></SafeAreaView>;
  return <SafeAreaView style={styles.page}><View style={styles.header}><Text style={styles.title}>{workspace?.name ?? "스기"}</Text><TouchableOpacity onPress={() => load().catch((reason) => setError(String(reason)))}><Text style={styles.link}>새로고침</Text></TouchableOpacity></View>{error ? <Text style={styles.error}>{error}</Text> : null}{tab === "home" && <Home workspace={workspace!} />}{tab === "chat" && <Chat workspace={workspace!} />}{tab === "notice" && <Notices workspace={workspace!} />}{tab === "profile" && <Profile workspaces={workspaces} workspace={workspace!} onSelect={setWorkspace} onLogout={() => { api.setToken(); setWorkspace(undefined); }} />}<View style={styles.tabbar}>{tabs.map(([key, label]) => <TouchableOpacity key={key} onPress={() => setTab(key)} style={styles.tab}><Text style={tab === key ? styles.activeTab : styles.inactiveTab}>{label}</Text></TouchableOpacity>)}</View></SafeAreaView>;
}

function Home({ workspace }: { workspace: Workspace }) { const [tasks, setTasks] = useState<Task[]>([]); const [timetable, setTimetable] = useState<Timetable[]>([]); useEffect(() => { api.tasks(workspace.id).then((x) => setTasks(x.data ?? [])).catch(() => undefined); api.timetable(workspace.id).then((x) => setTimetable(x.data ?? [])).catch(() => undefined); }, [workspace.id]); return <FlatList style={styles.content} data={tasks} keyExtractor={(item) => item.id} ListHeaderComponent={<><Card title="오늘의 시간표">{timetable.length ? timetable.map((item) => <Text key={item.id}>{item.period}교시 · {item.subject}</Text>) : <Text>등록된 시간표가 없습니다.</Text>}</Card><Card title="과제"><Text>{tasks.length}개의 과제가 있습니다.</Text></Card><CatSeugi /></>} renderItem={({ item }) => <Card title={item.title}><Text>{item.dueDate ? `마감 ${new Date(item.dueDate).toLocaleDateString()}` : "마감일 없음"}</Text></Card>} />; }
function CatSeugi() { const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState(""); return <Card title="캣스기"><TextInput value={question} onChangeText={setQuestion} style={styles.input} placeholder="무엇이든 물어보세요" /><Button label="질문하기" onPress={() => api.askCatSeugi(question).then((x) => setAnswer(x.data ?? "")).catch((e) => setAnswer(e.message))} />{answer ? <Text style={styles.answer}>{answer}</Text> : null}</Card>; }
function Chat({ workspace }: { workspace: Workspace }) { const [rooms, setRooms] = useState<Room[]>([]); useEffect(() => { api.rooms(workspace.id).then((x) => setRooms(x.data ?? [])).catch(() => undefined); }, [workspace.id]); return <FlatList style={styles.content} data={rooms} keyExtractor={(item) => item.id} ListEmptyComponent={<Text style={styles.empty}>아직 참여한 채팅방이 없습니다.</Text>} renderItem={({ item }) => <TouchableOpacity style={styles.row} onPress={() => Alert.alert(item.name, "메시지 화면은 Socket.IO로 연결됩니다.")}><Text style={styles.rowTitle}>{item.name}</Text><Text>{item.memberIds.length}명</Text></TouchableOpacity>} />; }
function Notices({ workspace }: { workspace: Workspace }) { const [items, setItems] = useState<Notification[]>([]); useEffect(() => { api.notifications(workspace.id).then((x) => setItems(x.data ?? [])).catch(() => undefined); }, [workspace.id]); return <FlatList style={styles.content} data={items} keyExtractor={(item) => item.id} ListEmptyComponent={<Text style={styles.empty}>새 공지가 없습니다.</Text>} renderItem={({ item }) => <Card title={item.title}><Text>{item.content}</Text><Text style={styles.muted}>{new Date(item.createdAt).toLocaleString()}</Text></Card>} />; }
function Profile({ workspaces, workspace, onSelect, onLogout }: { workspaces: Workspace[]; workspace: Workspace; onSelect: (value: Workspace) => void; onLogout: () => void }) { return <View style={styles.content}><Card title="워크스페이스">{workspaces.map((item) => <TouchableOpacity key={item.id} onPress={() => onSelect(item)}><Text style={item.id === workspace.id ? styles.activeTab : styles.rowTitle}>{item.name}</Text></TouchableOpacity>)}</Card><Button label="로그아웃" kind="secondary" onPress={onLogout} /></View>; }
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.card}><Text style={styles.cardTitle}>{title}</Text>{children}</View>; }
function Button({ label, onPress, kind = "primary", disabled }: { label: string; onPress: () => void; kind?: "primary" | "secondary"; disabled?: boolean }) { return <TouchableOpacity disabled={disabled} onPress={onPress} style={[styles.button, kind === "secondary" && styles.secondary, disabled && styles.disabled]}><Text style={kind === "primary" ? styles.buttonText : styles.secondaryText}>{label}</Text></TouchableOpacity>; }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: "#F7F8FC" }, auth: { flex: 1, justifyContent: "center", padding: 24, backgroundColor: "#F7F8FC" }, logo: { color: "#286BFF", fontWeight: "800", fontSize: 36, textAlign: "center" }, subtitle: { textAlign: "center", color: "#6B7280", marginVertical: 24 }, header: { height: 58, backgroundColor: "#FFF", paddingHorizontal: 20, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, title: { fontSize: 20, fontWeight: "700" }, link: { color: "#286BFF" }, content: { flex: 1, padding: 16 }, input: { backgroundColor: "#FFF", borderWidth: 1, borderColor: "#E5E7EB", borderRadius: 10, padding: 13, marginBottom: 10 }, button: { backgroundColor: "#286BFF", padding: 14, borderRadius: 10, alignItems: "center", marginBottom: 10 }, secondary: { backgroundColor: "#EAF0FF" }, buttonText: { color: "#FFF", fontWeight: "700" }, secondaryText: { color: "#286BFF", fontWeight: "700" }, disabled: { opacity: 0.5 }, card: { backgroundColor: "#FFF", borderRadius: 14, padding: 16, marginBottom: 12, gap: 8 }, cardTitle: { fontSize: 17, fontWeight: "700" }, tabbar: { height: 64, flexDirection: "row", backgroundColor: "#FFF", borderTopWidth: 1, borderColor: "#E5E7EB" }, tab: { flex: 1, justifyContent: "center", alignItems: "center" }, activeTab: { color: "#286BFF", fontWeight: "700" }, inactiveTab: { color: "#9CA3AF" }, row: { backgroundColor: "#FFF", padding: 16, marginBottom: 8, borderRadius: 12, flexDirection: "row", justifyContent: "space-between" }, rowTitle: { fontWeight: "600" }, muted: { color: "#9CA3AF", fontSize: 12 }, error: { color: "#DC2626", marginVertical: 8, textAlign: "center" }, empty: { color: "#6B7280", textAlign: "center", padding: 30 }, answer: { backgroundColor: "#EEF2FF", padding: 10, borderRadius: 8 } });
