import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, FlatList, SafeAreaView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import * as SecureStore from "expo-secure-store";
import { io } from "socket.io-client";
import { SeugiApi } from "@seugi/api-client";
import type { ChatMessage, Notification, Room, Task, Timetable, Workspace } from "@seugi/contracts";
import { API_URL } from "./src/config";

type Tab = "home" | "chat" | "notice" | "profile";
const tabs: Array<[Tab, string]> = [["home", "홈"], ["chat", "채팅"], ["notice", "공지"], ["profile", "프로필"]];
const api = new SeugiApi(API_URL);
const accessTokenKey = "seugi.access-token";

export default function App() {
  const [tab, setTab] = useState<Tab>("home");
  const [workspace, setWorkspace] = useState<Workspace>();
  const [workspaces, setWorkspaces] = useState<Workspace[]>([]);
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [name, setName] = useState(""); const [code, setCode] = useState("");
  const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [hydrated, setHydrated] = useState(false);
  const signedIn = !!workspace;
  const load = useCallback(async () => { const list = (await api.workspaces()).data ?? []; setWorkspaces(list); setWorkspace((current) => current && list.find((item) => item.id === current.id) || list[0]); }, []);
  useEffect(() => { let active = true; (async () => { const token = await SecureStore.getItemAsync(accessTokenKey); if (token) { api.setToken(token); try { await load(); } catch { api.setToken(); await SecureStore.deleteItemAsync(accessTokenKey); } } if (active) setHydrated(true); })().catch(() => active && setHydrated(true)); return () => { active = false; }; }, [load]);
  const authenticate = useCallback(async (register = false) => { setLoading(true); setError(""); try { const response = register ? await api.register({ email, password, name, code }) : await api.login({ email, password }); const token = response.data?.accessToken; if (!token) throw new Error("액세스 토큰을 받지 못했습니다"); api.setToken(token); await load(); await SecureStore.setItemAsync(accessTokenKey, token); } catch (reason) { setError(reason instanceof Error ? reason.message : "로그인에 실패했습니다"); } finally { setLoading(false); } }, [email, password, name, code, load]);
  if (!hydrated) return <SafeAreaView style={styles.auth}><ActivityIndicator size="large" color="#286BFF" /><Text style={styles.subtitle}>로그인 정보를 확인하는 중…</Text></SafeAreaView>;
  if (!signedIn) return <SafeAreaView style={styles.auth}><Text style={styles.logo}>스기</Text><Text style={styles.subtitle}>학교의 모든 소통을 한 곳에서</Text><TextInput placeholder="이메일" autoCapitalize="none" style={styles.input} value={email} onChangeText={setEmail} /><TextInput placeholder="비밀번호 (8자 이상)" secureTextEntry style={styles.input} value={password} onChangeText={setPassword} /><TextInput placeholder="이름 (회원가입 시)" style={styles.input} value={name} onChangeText={setName} /><TextInput placeholder="이메일 인증 코드 (회원가입 시)" keyboardType="number-pad" style={styles.input} value={code} onChangeText={setCode} />{error ? <Text style={styles.error}>{error}</Text> : null}<Button label="인증 코드 보내기" kind="secondary" onPress={() => api.sendVerification(email).then(() => setError("인증 코드를 발송했습니다.")).catch((e) => setError(e.message))} disabled={!email || loading} /><Button label={loading ? "처리 중…" : "로그인"} onPress={() => authenticate(false)} disabled={loading} /><Button label="이메일로 회원가입" kind="secondary" onPress={() => authenticate(true)} disabled={loading} /></SafeAreaView>;
  return <SafeAreaView style={styles.page}><View style={styles.header}><Text style={styles.title}>{workspace?.name ?? "스기"}</Text><TouchableOpacity onPress={() => load().catch((reason) => setError(String(reason)))}><Text style={styles.link}>새로고침</Text></TouchableOpacity></View>{error ? <Text style={styles.error}>{error}</Text> : null}{tab === "home" && <Home workspace={workspace!} />}{tab === "chat" && <Chat workspace={workspace!} />}{tab === "notice" && <Notices workspace={workspace!} />}{tab === "profile" && <Profile workspaces={workspaces} workspace={workspace!} onSelect={setWorkspace} onLogout={async () => { api.setToken(); await SecureStore.deleteItemAsync(accessTokenKey); setWorkspace(undefined); }} />}<View style={styles.tabbar}>{tabs.map(([key, label]) => <TouchableOpacity key={key} onPress={() => setTab(key)} style={styles.tab}><Text style={tab === key ? styles.activeTab : styles.inactiveTab}>{label}</Text></TouchableOpacity>)}</View></SafeAreaView>;
}

function Home({ workspace }: { workspace: Workspace }) { const [tasks, setTasks] = useState<Task[]>([]); const [timetable, setTimetable] = useState<Timetable[]>([]); useEffect(() => { api.tasks(workspace.id).then((x) => setTasks(x.data ?? [])).catch(() => undefined); api.timetable(workspace.id).then((x) => setTimetable(x.data ?? [])).catch(() => undefined); }, [workspace.id]); return <FlatList style={styles.content} data={tasks} keyExtractor={(item) => item.id} ListHeaderComponent={<><Card title="오늘의 시간표">{timetable.length ? timetable.map((item) => <Text key={item.id}>{item.period}교시 · {item.subject}</Text>) : <Text>등록된 시간표가 없습니다.</Text>}</Card><Card title="과제"><Text>{tasks.length}개의 과제가 있습니다.</Text></Card><CatSeugi /></>} renderItem={({ item }) => <Card title={item.title}><Text>{item.dueDate ? `마감 ${new Date(item.dueDate).toLocaleDateString()}` : "마감일 없음"}</Text></Card>} />; }
function CatSeugi() { const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState(""); return <Card title="캣스기"><TextInput value={question} onChangeText={setQuestion} style={styles.input} placeholder="무엇이든 물어보세요" /><Button label="질문하기" onPress={() => api.askCatSeugi(question).then((x) => setAnswer(x.data ?? "")).catch((e) => setAnswer(e.message))} />{answer ? <Text style={styles.answer}>{answer}</Text> : null}</Card>; }
function Chat({ workspace }: { workspace: Workspace }) { const [rooms, setRooms] = useState<Room[]>([]); const [selected, setSelected] = useState<Room>(); useEffect(() => { setSelected(undefined); api.rooms(workspace.id).then((x) => setRooms(x.data ?? [])).catch(() => undefined); }, [workspace.id]); if (selected) return <RoomMessages room={selected} onBack={() => setSelected(undefined)} />; return <FlatList style={styles.content} data={rooms} keyExtractor={(item) => item.id} ListEmptyComponent={<Text style={styles.empty}>아직 참여한 채팅방이 없습니다.</Text>} renderItem={({ item }) => <TouchableOpacity style={styles.row} onPress={() => setSelected(item)}><Text style={styles.rowTitle}>{item.name}</Text><Text>{item.memberIds.length}명</Text></TouchableOpacity>} />; }
function RoomMessages({ room, onBack }: { room: Room; onBack: () => void }) { const [messages, setMessages] = useState<ChatMessage[]>([]); const [draft, setDraft] = useState(""); const [sending, setSending] = useState(false); useEffect(() => { const socket = io(API_URL, { auth: { token: api.accessToken() } }); api.messages(room.id).then((result) => setMessages((result.data?.messages ?? []).reverse())).catch(() => undefined); socket.on("connect", () => socket.emit("room:join", room.id)); socket.on("chat:message", (message: ChatMessage) => { if (message.roomId === room.id) setMessages((current) => [...current, message]); }); return () => { socket.close(); }; }, [room.id]); const send = () => { const text = draft.trim(); if (!text || sending) return; setSending(true); const socket = io(API_URL, { auth: { token: api.accessToken() } }); socket.on("connect", () => { socket.emit("room:join", room.id); socket.emit("chat:message", { roomId: room.id, message: text }, (result: { message: string }) => { setSending(false); socket.close(); if (result.message === "메시지 전송 성공") setDraft(""); else Alert.alert("전송 실패", result.message); }); }); }; return <View style={styles.chatPage}><View style={styles.chatHeader}><TouchableOpacity onPress={onBack}><Text style={styles.link}>‹ 목록</Text></TouchableOpacity><Text style={styles.rowTitle}>{room.name}</Text></View><FlatList style={styles.content} data={messages} keyExtractor={(item) => item.id} renderItem={({ item }) => <View style={styles.message}><Text>{item.message}</Text><Text style={styles.muted}>{new Date(item.createdAt).toLocaleTimeString()}</Text></View>} /><View style={styles.composer}><TextInput value={draft} onChangeText={setDraft} placeholder="메시지 입력" style={[styles.input, styles.composerInput]} onSubmitEditing={send} /><Button label={sending ? "…" : "전송"} onPress={send} disabled={sending} /></View></View>; }
function Notices({ workspace }: { workspace: Workspace }) { const [items, setItems] = useState<Notification[]>([]); useEffect(() => { api.notifications(workspace.id).then((x) => setItems(x.data ?? [])).catch(() => undefined); }, [workspace.id]); return <FlatList style={styles.content} data={items} keyExtractor={(item) => item.id} ListEmptyComponent={<Text style={styles.empty}>새 공지가 없습니다.</Text>} renderItem={({ item }) => <Card title={item.title}><Text>{item.content}</Text><Text style={styles.muted}>{new Date(item.createdAt).toLocaleString()}</Text></Card>} />; }
function Profile({ workspaces, workspace, onSelect, onLogout }: { workspaces: Workspace[]; workspace: Workspace; onSelect: (value: Workspace) => void; onLogout: () => void }) { return <View style={styles.content}><Card title="워크스페이스">{workspaces.map((item) => <TouchableOpacity key={item.id} onPress={() => onSelect(item)}><Text style={item.id === workspace.id ? styles.activeTab : styles.rowTitle}>{item.name}</Text></TouchableOpacity>)}</Card><Button label="로그아웃" kind="secondary" onPress={onLogout} /></View>; }
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.card}><Text style={styles.cardTitle}>{title}</Text>{children}</View>; }
function Button({ label, onPress, kind = "primary", disabled }: { label: string; onPress: () => void; kind?: "primary" | "secondary"; disabled?: boolean }) { return <TouchableOpacity disabled={disabled} onPress={onPress} style={[styles.button, kind === "secondary" && styles.secondary, disabled && styles.disabled]}><Text style={kind === "primary" ? styles.buttonText : styles.secondaryText}>{label}</Text></TouchableOpacity>; }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: "#F7F8FC" }, auth: { flex: 1, justifyContent: "center", padding: 24, backgroundColor: "#F7F8FC" }, logo: { color: "#286BFF", fontWeight: "800", fontSize: 36, textAlign: "center" }, subtitle: { textAlign: "center", color: "#6B7280", marginVertical: 24 }, header: { height: 58, backgroundColor: "#FFF", paddingHorizontal: 20, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, title: { fontSize: 20, fontWeight: "700" }, link: { color: "#286BFF" }, content: { flex: 1, padding: 16 }, input: { backgroundColor: "#FFF", borderWidth: 1, borderColor: "#E5E7EB", borderRadius: 10, padding: 13, marginBottom: 10 }, button: { backgroundColor: "#286BFF", padding: 14, borderRadius: 10, alignItems: "center", marginBottom: 10 }, secondary: { backgroundColor: "#EAF0FF" }, buttonText: { color: "#FFF", fontWeight: "700" }, secondaryText: { color: "#286BFF", fontWeight: "700" }, disabled: { opacity: 0.5 }, card: { backgroundColor: "#FFF", borderRadius: 14, padding: 16, marginBottom: 12, gap: 8 }, cardTitle: { fontSize: 17, fontWeight: "700" }, tabbar: { height: 64, flexDirection: "row", backgroundColor: "#FFF", borderTopWidth: 1, borderColor: "#E5E7EB" }, tab: { flex: 1, justifyContent: "center", alignItems: "center" }, activeTab: { color: "#286BFF", fontWeight: "700" }, inactiveTab: { color: "#9CA3AF" }, row: { backgroundColor: "#FFF", padding: 16, marginBottom: 8, borderRadius: 12, flexDirection: "row", justifyContent: "space-between" }, rowTitle: { fontWeight: "600" }, muted: { color: "#9CA3AF", fontSize: 12 }, error: { color: "#DC2626", marginVertical: 8, textAlign: "center" }, empty: { color: "#6B7280", textAlign: "center", padding: 30 }, answer: { backgroundColor: "#EEF2FF", padding: 10, borderRadius: 8 }, chatPage: { flex: 1 }, chatHeader: { backgroundColor: "#FFF", padding: 16, flexDirection: "row", gap: 16, alignItems: "center" }, message: { backgroundColor: "#FFF", borderRadius: 12, padding: 12, marginBottom: 8, alignSelf: "flex-start", maxWidth: "85%" }, composer: { flexDirection: "row", padding: 10, gap: 8, backgroundColor: "#FFF", alignItems: "center" }, composerInput: { flex: 1, marginBottom: 0 } });
